simulator_type: maniskill
auto_reset: True
ignore_terminations: True
use_rel_reward: True
seed: 0
num_group: ${env.eval.num_envs}
group_size: 1
use_fixed_reset_state_ids: True
num_envs: 8
only_eval: True

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  id: PutOnPlateInScene25Main-v3
  num_envs: 4
  obs_mode: ${env.train.init_params.obs_mode}
  control_mode: None
  sim_backend: "gpu"
  sim_config: ${env.train.init_params.sim_config}
  max_episode_steps: ${env.train.init_params.max_episode_steps}
  sensor_configs: ${env.train.init_params.sensor_configs}
  render_mode: all
  obj_set: test