simulator_type: behavior
auto_reset: ${algorithm.auto_reset}
ignore_terminations: ${algorithm.ignore_terminations}
use_rel_reward: True
seed: 0
num_group: ${algorithm.num_group_envs}
group_size: ${algorithm.group_size}
use_fixed_reset_state_ids: ${algorithm.use_fixed_reset_state_ids}
max_episode_steps: 2000
max_steps: 2000
only_eval: False
image_size: [224, 224]

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

base_config_name: r1pro_behavior
num_envs: ${algorithm.num_group_envs}

tasks:
  activity_task_indices: "0" # eg. "0-49" or "0-20,49"
  task_description_path: examples/embodiment/config/env/behavior_task.jsonl
