simulator_type: libero
task_suite_name: libero_spatial

auto_reset: ${algorithm.auto_reset}
ignore_terminations: ${algorithm.ignore_terminations}
max_episode_steps: ${algorithm.max_episode_steps}

use_rel_reward: True
reward_coef: ${algorithm.reward_coef}
only_eval: False

seed: 0
num_group: ${algorithm.num_group_envs}
group_size: ${algorithm.group_size}
use_fixed_reset_state_ids: ${algorithm.use_fixed_reset_state_ids}
use_wrist_image: ${actor.model.use_wrist_image}

num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}

specific_reset_id: ${algorithm.specific_reset_id}

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  camera_heights: 256
  camera_widths: 256

use_ordered_reset_state_ids: ${algorithm.use_ordered_reset_state_ids}