name: Agent/Reason End-to-End Tests

on:
  workflow_call:

jobs:
  reason-qwen-grpo-test:
    runs-on: reason
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Megatron SGLang Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-collocated-mg-sgl

      - name: Megatron vLLM Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-collocated-mg-vllm

      - name: Megatron SGLang Pipeline mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-pipeline-mg-sgl

      - name: Megatron vLLM Pipeline mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-pipeline-mg-vllm

      - name: FSDP SGLang Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-collocated-fsdp-sgl

      - name: FSDP vLLM Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-collocated-fsdp-vllm


  reason-qwen-grpo-test-rollout-logprobs:
    runs-on: reason
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Megatron SGLang Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-collocated-mg-sgl-rollout-logprobs

      - name: Megatron vLLM Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-collocated-mg-vllm-rollout-logprobs

      - name: Megatron SGLang Pipeline mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-pipeline-mg-sgl-rollout-logprobs

      - name: Megatron vLLM Pipeline mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-pipeline-mg-vllm-rollout-logprobs

      - name: FSDP SGLang Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-collocated-fsdp-sgl-rollout-logprobs

      - name: FSDP vLLM Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-grpo-collocated-fsdp-vllm-rollout-logprobs

  reason-qwen-importance-sampling-test:
    runs-on: reason
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
  
      - name: Megatron SGLang Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-is-collocated-mg-sgl

  reason-qwen-reinforcepp-test:
    runs-on: reason
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
  
      - name: Megatron SGLang Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-1.5b-reinpp-collocated-mg-sgl

  coding-online-rl-qwen-ppo-test:
    runs-on: reason
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          pip install httpx asyncio fuzzywuzzy

      - name: SGLang Pipeline mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/coding_online_rl/run.sh

  qwen-vl-grpo-test:
    runs-on: reason
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: FSDP SGLang Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-vl-3b-grpo-collocated-fsdp-sgl

      - name: FSDP vLLM Collocated mode
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen2.5-vl-3b-grpo-collocated-fsdp-vllm

  agent-rl-qwen-ppo-test:
    runs-on: reason
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Megatron SGLang Pipeline mode
        timeout-minutes: 10
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/agent/run_tool.sh

  qwen-moe-grpo-test:
    runs-on: reason
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: MoE sequential MLP Collocated mode 
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen3-moe-2.5b-collocated-mg-sgl-sequentialmlp
          rm -rf /workspace/results/grpo-moe-CI-test-seqmlp-2.5b/converted_ckpts/
      
      - name: MoE TeGroupgemm MLP Collocated mode 
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen3-moe-2.5b-collocated-mg-sgl-tegroupgemm
          rm -rf /workspace/results/grpo-moe-CI-test-seqmlp-2.5b/converted_ckpts/

      - name: MoE model parallel ep test 
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen3-moe-2.5b-collocated-mg-sgl-ep-test
          rm -rf /workspace/results/grpo-moe-CI-test-seqmlp-2.5b/converted_ckpts/
        
      - name: MoE model parallel tpe test 
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen3-moe-2.5b-collocated-mg-sgl-tpe-test
          rm -rf /workspace/results/grpo-moe-CI-test-seqmlp-2.5b/converted_ckpts/
      
      - name: MoE model parallel tp test 
        timeout-minutes: 20
        run: |
          export REPO_PATH=$(pwd)
          source switch_env reason
          bash tests/e2e_tests/reasoning/run.sh qwen3-moe-2.5b-collocated-mg-sgl-tp-test
          rm -rf /workspace/results/grpo-moe-CI-test-seqmlp-2.5b/converted_ckpts/
